import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Terms of Service - Trellis",
  description:
    "The terms that govern your use of Trellis — including acceptable use, AI-generated content, and disclaimers for a hackathon-stage service.",
};

const LAST_UPDATED = "May 29, 2026";
const CONTACT_EMAIL = "trellis@davidumoru.me";

export default function TermsPage() {
  return (
    <div className="min-h-svh bg-background text-foreground">
      <SiteHeader />
      <main className="mx-auto w-full max-w-3xl px-8 pt-16 pb-24">
        <div className="mb-12">
          <h1 className="font-heading text-4xl font-medium leading-[1.1] tracking-[-0.02em] sm:text-5xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-sm text-muted-foreground">
            Last updated {LAST_UPDATED}
          </p>
        </div>

        <Prose>
          <p>
            These terms (“Terms”) govern your access to and use of Trellis (the
            “Service”), provided as a personal job-search assistant built for
            the 2026 Google Cloud Rapid Agent Hackathon. By creating an account or
            using the Service you agree to these Terms.
          </p>

          <H2 id="eligibility">1. Eligibility</H2>
          <p>
            You must be at least 16 years old to use Trellis. By using the
            Service you represent that you are eligible to enter into a binding
            agreement.
          </p>

          <H2 id="account">2. Your account</H2>
          <p>
            You are responsible for safeguarding your sign-in credentials and
            for any activity that occurs under your account. Notify us at{" "}
            {CONTACT_EMAIL} if you suspect unauthorized access. We use one-time
            passcodes and Google OAuth; you should not share your inbox or your
            OTPs with anyone.
          </p>

          <H2 id="acceptable-use">3. Acceptable use</H2>
          <p>You agree not to:</p>
          <ul>
            <li>
              Use the Service to violate any law or the rights of others,
              including by sending unsolicited messages or impersonating
              someone.
            </li>
            <li>
              Reverse engineer, scrape at scale, or attempt to derive the source
              code or model weights underlying the Service.
            </li>
            <li>
              Probe, scan, or test the vulnerability of any system or network
              connected to the Service without authorization.
            </li>
            <li>
              Upload or transmit content that is illegal, malicious, defamatory,
              or that you do not have the right to share.
            </li>
            <li>
              Use the Service to make automated decisions about other people
              (e.g., automated screening of candidates) without their consent.
            </li>
          </ul>

          <H2 id="your-content">4. Your content</H2>
          <p>
            You retain all rights to the data you upload, paste, or connect to
            Trellis (“Your Content”), including your applications, resumes,
            notes, and the Gmail and Calendar data you authorize us to read. You
            grant Trellis a limited license to host, process, and display Your
            Content solely to provide the Service to you.
          </p>
          <p>
            You are responsible for ensuring you have the right to share Your
            Content with Trellis. If a recruiter or third party is identifiable
            in a message you connect, you confirm that your processing of that
            information complies with applicable privacy law.
          </p>

          <H2 id="ai-output">5. AI-generated content</H2>
          <p>
            Parts of the Service use large language models to draft resumes,
            cover letters, and answers. AI output can be inaccurate, outdated,
            biased, or fabricated. You are responsible for reviewing, verifying,
            and editing AI output before sending it to a recruiter or relying on
            it for any decision. Do not treat AI-generated content as legal,
            financial, or career advice.
          </p>
          <p>
            Output generated by the Service is provided to you without ownership
            claims by Trellis; however, AI output may resemble content produced
            by other users or available publicly, and we make no representation
            that it is free of similar third-party content.
          </p>

          <H2 id="third-parties">6. Third-party services</H2>
          <p>
            The Service integrates with third parties including Google (Gmail,
            Calendar, OAuth), MongoDB Atlas (data storage), the Vercel AI
            Gateway, and Google Vertex AI / Gemini (model inference). Your use
            of those services is governed by their respective terms. We are not
            responsible for outages, limits, or policy changes by those
            providers.
          </p>

          <H2 id="termination">7. Termination</H2>
          <p>
            You may stop using the Service and delete your account at any time.
            We may suspend or terminate your access if you violate these Terms,
            if required to comply with law, or if continuing to provide the
            Service to you would create significant risk. We will provide
            reasonable notice where possible.
          </p>
          <p>
            On termination, the rights you grant in these Terms end and we will
            delete Your Content per the schedule in our{" "}
            <a href="/privacy">Privacy Policy</a>.
          </p>

          <H2 id="disclaimer">8. Disclaimers</H2>
          <p>
            Trellis is provided <strong>as is</strong> and{" "}
            <strong>as available</strong>, without warranties of any kind,
            express or implied, including merchantability, fitness for a
            particular purpose, and non-infringement. We do not warrant that the
            Service will be uninterrupted, error-free, secure, or that results
            obtained from using the Service will be accurate or reliable. The
            Service is a hackathon-stage project and may change, break, or be
            discontinued without notice.
          </p>

          <H2 id="liability">9. Limitation of liability</H2>
          <p>
            To the maximum extent permitted by law, in no event will Trellis,
            its operators, or contributors be liable for any indirect,
            incidental, special, consequential, or punitive damages, or for any
            loss of profits, revenues, data, or goodwill, arising out of or
            related to your use of or inability to use the Service. Our total
            aggregate liability for any claim arising out of or related to these
            Terms or the Service will not exceed one hundred US dollars ($100).
          </p>

          <H2 id="indemnity">10. Indemnity</H2>
          <p>
            You agree to defend and indemnify Trellis from claims arising out of
            (i) Your Content, (ii) your use of the Service in violation of these
            Terms or applicable law, or (iii) your violation of any third
            party’s rights.
          </p>

          <H2 id="changes">11. Changes to these Terms</H2>
          <p>
            We may update these Terms as the Service evolves. Material changes
            will be reflected in the “Last updated” date above and, where
            appropriate, communicated by email. Continued use of the Service
            after a change means you accept the updated Terms.
          </p>

          <H2 id="contact">12. Contact</H2>
          <p>
            Questions about these Terms can be sent to{" "}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
        </Prose>
      </main>
      <SiteFooter />
    </div>
  );
}

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="
        flex flex-col gap-4 text-sm leading-relaxed text-muted-foreground
        [&_a]:text-foreground [&_a]:underline [&_a]:underline-offset-2 [&_a:hover]:text-foreground/80
        [&_strong]:font-medium [&_strong]:text-foreground
        [&_ul]:flex [&_ul]:list-disc [&_ul]:flex-col [&_ul]:gap-2 [&_ul]:pl-6
        [&_p]:mt-0
      "
    >
      {children}
    </div>
  );
}

function H2({ id, children }: { id: string; children: React.ReactNode }) {
  return (
    <h2
      id={id}
      className="font-heading mt-10 scroll-mt-24 text-xl font-medium tracking-tight text-foreground"
    >
      {children}
    </h2>
  );
}
